# Example Helm values for running the Infra connector against a local dev server.
# Update `config.server.url`, `config.accessKey`, and `service.loadBalancerIP`
# for your environment before running:
#
#   helm upgrade --install infra infrahq/infra \
#     --namespace infra --create-namespace --wait \
#     --atomic --version 0.1.2 -f dev/connector-values.yaml
config:
  server:
    url: https://172.21.199.19:9443
    trustedCertificate: |
      -----BEGIN CERTIFICATE-----
      MIIDDzCCAfegAwIBAgIUWp7wzhCFK0K5GSu3fJAI630aPrUwDQYJKoZIhvcNAQEL
      BQAwFzEVMBMGA1UEAwwMSW5mcmEgRGV2IENBMB4XDTI1MTExMzIyNTg1M1oXDTM1
      MTExMTIyNTg1M1owFzEVMBMGA1UEAwwMSW5mcmEgRGV2IENBMIIBIjANBgkqhkiG
      9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwg5oGsbQHI08fkIAt0FBpIq6hkAognw76N1t
      rjGGzgn2tAMogHy2ikHMDhvuJcDi1rOtu7L+1EvkAmQ6NE/Hjh5Yt8VcNQdgKRvJ
      SOn86KBX1vlMyOkKEU480/oirTOmKJ/dxo3Oxz76fN2DQtVnTIwRgyD+9d3uOFqn
      ikh+sVhu7PYsDh2FSr4kKxb4SrU1vaYnqUMrcUgPZyjiOGqfHMqw35jPWRGO7oxi
      T5IPRZT5xK1gJtNthzgQh3vuQcog/7TnCb1lpFda1MxQkH376AXDEq4dnkAN1/Ip
      CXZtjNNTsgXz8e7ns0NtmzaG/QWr8axFRkMMHs9ftdW5llVkywIDAQABo1MwUTAd
      BgNVHQ4EFgQUqSYANpWYy0vPPtuIg7WgJ0b0+i8wHwYDVR0jBBgwFoAUqSYANpWY
      y0vPPtuIg7WgJ0b0+i8wDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOC
      AQEAgmSqpTBALDWnLpulqrlSq06ElrOGPHVDGRAsQMQ9c5X9RbejnvHBpd7FIHqx
      kPU+YlEEbcxFSR7MBjTVSdCMhY2R9Lg6iXWwLeNJRdAbXJNlx+sOTCrJWESZ5/Yk
      07mSv5iz7aI1KgNLlVEfYMM8lbysmzMmQGlZQ7Q+pFeGrkQA9l2EZC6wX4UuFnaX
      L6cAL5eJHyAQw61RNM3XXvu7dY+WT6ivPIZyR9SrqqbCHU5YEcNfQbz564vTdXly
      OH81pI6KiMcR5RjVX0AfsQb31FjyWDGWvwqO4zopIVVhSNL4IzB2A5OhIMmtq/3l
      7pe/4rPE5iJ8sBLiUX8BbErgVQ==
      -----END CERTIFICATE-----
  name: test-k8s
  accessKey: iv0bYbZBxJ.hHO31YzYcshnFBXkqhlZng0A

service:
  type: LoadBalancer
  loadBalancerIP: 192.168.49.96


image:
  repository: registry.gitlab.com/ska-telescope/external/infra/infra
  tag: 0.21.7
  pullPolicy: IfNotPresent
